apiVersion: wildfly.org/v1alpha1
kind: WildFlyServer
metadata:
  name: clusterbench
spec:
  applicationImage: "quay.io/wildfly-quickstarts/clusterbench-ee7:17.0"
  size: 2
  standaloneConfigMap:
    name: clusterbench-config-map
    key: standalone-openshift.xml
